### PR TITLE
Get hubpack from crates.io.

### PR DESCRIPTION
**Pull request by flihp**

### CODE REVIEW

**Comment by flihp** [comment]
PR updated to use shorter dependency form.

**Review by andrewjstone — APPROVED** [review]
LGTM. I can't believe the last update to hubpack was 7 months ago. As Ferris Bueller said: "Life comes at you fast"

**Comment by flihp** [comment]
this is blocked in #41 (clippy-link is a required check)

**Comment by andrewjstone** [comment]
@flihp Can you please rebase this along with #39 and #42 when you get a chance please?

**Pull request merged**
